server:
  port: 8189
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onlineshop;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  redis:
    host: "172.24.161.125"
    port: 6379
jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r
  lifetime: 36000000