server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8193
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-order
        - id: auth-service
          uri: http://localhost:8190
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: http://localhost:8191
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8188"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
jwt:
  secret: oifh4309f8h324#098fh4398gh8h*&TG*#&Gg97rgf&-f98gf983h4f983h487g*&^F&Fu3r

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE