server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core-service/**
          filters:
            - StripPrefix=1
        - id: order-service
            uri: http://localhost:8193
            predicates:
              - Path=/order-service/**
              - PrefixPath=/market-order
            filters:
              - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
jwt:
  secret: oifh4309f8h324#098fh4398gh8h*&TG*#&Gg97rgf&-f98gf983h4f983h487g*&^F&Fu3r

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE